# Default values for starter-chart.
replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""
  # command: ["start"]
  # args: ["-v"]

initContainers: []

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

configmap:
  env: {}
  files: {}

envFromFieldRef:
  - name: POD_NAME
    fieldPath: metadata.name
  - name: POD_NAMESPACE
    fieldPath: metadata.namespace
  - name: POD_IP
    fieldPath: status.podIP
  - name: NODE_NAME
    fieldPath: spec.nodeName
  - name: HOST_IP
    fieldPath: status.hostIP

volumes:
  files:
    mountPath: /mnt/files
  data:
    mountPath: /mnt/data

persistence:
  enabled: false
  annotations: {}
  accessModes:
    - ReadWriteOnce
  size: 1Gi

container:
  ports:
    - name: http
      containerPort: 80
    #prometheus:
    #  containerPort: 3000

service:
  - name: http
    port: 80
  #prometheus:
  #  type: ClusterIP
  #  port: 3000

prometheus: false

serviceAccount:
  create: true
  annotations: {}
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
