apiVersion: apps/v1
kind: {{ .Values.kind }}
metadata:
  name: {{ include "base.fullname" . }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "base.selectorLabels" . | nindent 6 }}
  {{ if eq .Values.kind "StatefulSet"  }}
  serviceName: {{ include "base.fullname" . }}
  {{ end }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "base.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "base.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{- range $key, $value := .Values.initContainers }}
        - name: "{{ $.Chart.Name }}-init-{{ $key }}"
          image: "{{ $value.image.repository }}:{{ $value.image.tag }}"
          imagePullPolicy: {{ $value.image.pullPolicy }}
          command:
            {{- toYaml $value.image.command | nindent 12 }}
          args: 
            {{- toYaml $value.image.args | nindent 12 }}
          env:
            {{- range $idx, $value := $.Values.envFromFieldRef }}
            - name: {{ $value.name }}
              valueFrom:
                fieldRef:
                  fieldPath: {{ $value.fieldPath }}
            {{ end }}
          envFrom:
            - configMapRef:
                name: {{ include "base.fullname" $ }}-env
          volumeMounts:
            - name: files
              mountPath: {{ $.Values.volumes.files.mountPath }}
            - name: data
              mountPath: {{ $.Values.volumes.data.mountPath }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: 
            {{- toYaml .Values.image.command | nindent 12 }}
          args: 
            {{- toYaml .Values.image.args | nindent 12 }}
          ports:
            {{- range $idx, $value := .Values.container.ports }}
            - name: {{ $value.name }}
              containerPort: {{ $value.containerPort }}
              protocol: {{ $value.protocol | default "TCP" }}
            {{ end }}
          env:
            {{- range $idx, $value := .Values.envFromFieldRef }}
            - name: {{ $value.name }}
              valueFrom:
                fieldRef:
                  fieldPath: {{ $value.fieldPath }}
            {{ end }}
          envFrom:
            - configMapRef:
                name: {{ include "base.fullname" . }}-env
          volumeMounts:
            - name: files
              mountPath: {{ .Values.volumes.files.mountPath }}
            - name: data
              mountPath: {{ .Values.volumes.data.mountPath }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: files
          configMap:
            name: {{ include "base.fullname" . }}-files
{{- if and .Values.persistence.enabled .Values.persistence.existingClaim }}
        - name: data
          persistentVolumeClaim:
{{- with .Values.persistence.existingClaim }}
            claimName: {{ tpl . $ }}
{{- end }}
{{- else if and .Values.persistence.enabled .Values.persistence.hostPath }}
        - name: data
          hostPath:
            path: {{ .Values.persistence.hostPath.path }}
            type: {{ .Values.persistence.hostPath.type }}
{{- else if not .Values.persistence.enabled }}
        - name: data
          emptyDir: {}
{{- else if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
  volumeClaimTemplates:
    - metadata:
        name: data
      {{- with .Values.persistence.annotations }}
        annotations:
        {{- range $key, $value := . }}
            {{ $key }}: {{ $value }}
        {{- end }}
      {{- end }}
      spec:
        accessModes:
        {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
        {{ include "base.storageClass" . }}
{{- end }}
