# Default values for chainlink.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: smartcontract/chainlink
  tag: 0.9.10
#  tag: 1.4.1-root
  pullPolicy: IfNotPresent
#  command: ["tail", "-f", "/dev/null"]
  command: ["chainlink", "local", "node"]
  args: ["-a", "/etc/chainlink/api", "-p", "/etc/chainlink/password"]
config:
  # Login Info
  ROOT: /chainlink
  API_LOGIN: |
    test@test.com
    TTTtesttesttests
  WALLET_PASSWORD: "TTTtesttesttests"
  # HTTP Security
  ALLOW_ORIGINS: "*"
  SECURE_COOKIES: "false"
  CHAINLINK_PORT: "6688"
  CHAINLINK_TLS_PORT: "0"
  # Database
  DATABASE_TIMEOUT: "0"
  DATABASE_URL: postgresql://postgres@postgresql:5432/chainlink?sslmode=disable
  # Ethereum
  ETH_URL: wss://ropsten.infura.io/ws/v3/a812451fbb3c476faaa7b4186cafdf63
  ETH_CHAIN_ID: "3"
  LINK_CONTRACT_ADDRESS: 0x20fE562d797A42Dcb3399062AE9546cd06f63280
  ### Logging ###
  # JSON_CONSOLE: "true"
  # LOG_LEVEL: warn
  # LOG_TO_DISK: "false"
  ### Secondary Ethereum Node ###
  # ETH_SECONDARY_URL: ""
  ### Chainlink Explorer ###
  # EXPLORER_ACCESS_KEY: ""
  # EXPLORER_SECRET: ""
  # EXPLORER_URL: wss://explorer.chain.link
  ### Gas Bumber ###
  # GAS_UPDATER_ENABLED: "true"
  # GAS_UPDATER_TRANSACTION_PERCENTILE: "71"
  # ETH_GAS_PRICE_DEFAULT: "1000000000"
  # ETH_GAS_BUMP_THRESHOLD: "5"
  # ETH_GAS_BUMP_WEI: "20000000000"
  # ETH_GAS_BUMP_PERCENT: "20"
  # ETH_MAX_GAS_PRICE_WEI: "2500000000000"
  ### Transaction Manager ###
  # CHAINLINK_TX_ATTEMPT_LIMIT: "25"
  # ETH_MAX_IN_FLIGHT_TRANSACTIONS: "128"
  # MIN_OUTGOING_CONFIRMATIONS: "2"
  # MINIMUM_CONTRACT_PAYMENT: "50000000000000000"
  ### Fluxmonitor Variables ###
  # ORACLE_CONTRACT_ADDRESS: ""
  # FLAGS_CONTRACT_ADDRESS: ""
  ### OCR Variables ###
  # OCR_TRACE_LOGGING: "true"
  # FEATURE_OFFCHAIN_REPORTING: "true"
  P2P_LISTEN_PORT: "30668"
  # P2P_ANNOUNCE_PORT: "30668"
  # P2P_ANNOUNCE_IP: "YOUR_NODE_IP"
  ### OCR Default job config ###
  # OCR_KEY_BUNDLE_ID: ""
  # P2P_PEER_ID: ""
  # OCR_TRANSMITTER_ADDRESS: ""
  # P2P_BOOTSTRAP_PEERS: ""
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

container:
  ports:
    http: 6688
    listener: 30668

volumes:
  config:
    mountPath: /etc/chainlink

service:
  type: ClusterIP
  http: 6688

serviceP2P:
  type: ClusterIP #Ignores, only created if NodePort
  listener: 30668

prometheus: false

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
