apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "geth.fullname" . }}-files-configmap
data:
  config.toml: |
{{ .Values.config | indent 4 }}
  genesis.json: |
{{ .Values.genesis | indent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "geth.fullname" . }}-env-configmap
data:
  {{- toYaml .Values.env | nindent 2 }}