# Default values for base.
replicaCount: 1

kind: StatefulSet #Deployment

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""
  # command: ["start"]
  # args: ["-v"]

initContainers: []

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

configmap:
  env: {}
  files: {}

secret: {}

envFromFieldRef:
  - name: POD_NAME
    fieldPath: metadata.name
  - name: POD_NAMESPACE
    fieldPath: metadata.namespace
  - name: POD_IP
    fieldPath: status.podIP
  - name: NODE_NAME
    fieldPath: spec.nodeName
  - name: HOST_IP
    fieldPath: status.hostIP

envFromSecretKeyRef:
  []
  #- name:
  #  key: #key from secret

container:
  ports:
    - name: http
      containerPort: 80
  volumes:
    - name: files
      mountPath: /mnt/files
      configMap: true
      persistence:
        enabled: false
    - name: data
      mountPath: /mnt/data
      persistence:
        enabled: false
        annotations: {}
        accessModes:
          - ReadWriteOnce
        size: 1Gi

service:
  - name: http
    port: 80
  #prometheus:
  #  type: ClusterIP
  #  port: 3000

prometheus: false

serviceAccount:
  create: true
  annotations: {}
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
